### ISSUE TITLE
[Question] Source for database

### ISSUE THREAD

**Issue by JoachimDorchies** [DEFAULTDNB/DEFAULTDNB.github.io#1]
Hello !

Thank you for your work !

May I ask what is the source of your database ?

**Comment by DEFAULTDNB** [comment]
Hi sorry, just seen this message. 

My sources include various dump sites and forums, gematsu, metacritic, orbispatches, GameFAQs, and private information.

**Comment by JoachimDorchies** [comment]
Thanks, I'll stick with your DB then !
